### ISSUE TITLE
ISS : Stage Base Qc Master Recipe attribute code not fetching

### ISSUE THREAD

**Issue by sujin1708** [astpl1998/Jyoti-Ceramic#338]
@karthikeyanamitysoft @raju-kurup  Kindly Check the below-mentioned issue on a priority basis

In the  Master recipe under stage-based QC, we are giving a mandatory field as" YES " to some QC attributes. while selecting each stage click on the transfer button to get the attribute code and then we have to save. In the multiline 18 QC Attribute to be displayed but only 17 is now displaying. 

Eg: Master Reciepe Code UAT :  MR1BHA644_1
      Master Recipe Code Live  :   FAL6TR1350090_1

![image](https://user-images.githubusercontent.com/47313592/128669163-f13f47c4-7789-43f8-9c7e-9ac9f14681ae.png)

Regards,
Sujin.M

**Comment by raju-kurup** [comment]
@karthikeyanamitysoft : please look into this issue and it is critical

**Comment by BalaramanM** [comment]
@sujin1708 
Pls find the below attached screenshot.'**ipd_ret_type**'This field should not be empty.Because of that only qualitative Multiline value is missing
![image_2021_08_09T10_48_27_188Z](https://user-images.githubusercontent.com/80749490/128697398-c9e35ee7-a733-4ee2-af50-9c5c580df5d6.png)
![image_2021_08_09T10_50_21_950Z](https://user-images.githubusercontent.com/80749490/128697407-2b8f71c6-0513-41d8-bee7-aa0a1eb87c70.png)

**Comment by sujin1708** [comment]
@BalaramanM attribute type is qualitative not required..please re-check

**Comment by karthikeyanamitysoft** [comment]
sp name : MCX_SpTransf_ui_mlspO
line no 239
Note : ipd_ret_type is empty(Null ) for Qualitative so that its not fetching.
[atribute_issue.zip](https://github.com/astpl1998/Jyoti-Ceramic/files/6967407/atribute_issue.zip)


REgards,
Karthi

**Comment by karthikeyanamitysoft** [comment]
![image](https://user-images.githubusercontent.com/40713407/129008899-19eea361-3369-4683-a4b5-0aed23ae3149.png)

**Comment by raju-kurup** [comment]
Issue is given to Ramco for rectification and Ramco commented to update SP1 and SP2
